version: "3"
services:
  docker:
    image: docker:24.0.7-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    expose:
      - 2375
  open-balena-delta:
    build: ./open-balena-delta
    privileged: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
